Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 11:49:29
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Apr/2016 11:50:46] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1679
[03/Apr/2016 11:50:48] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1840
[03/Apr/2016 11:50:54] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[03/Apr/2016 11:50:54] "GET /admin/ HTTP/1.1" 200 4593
[03/Apr/2016 11:50:54] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 434
[03/Apr/2016 11:50:54] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[03/Apr/2016 11:50:54] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[03/Apr/2016 14:25:19] "GET /admin/main/match/ HTTP/1.1" 200 3154
[03/Apr/2016 14:25:19] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6100
[03/Apr/2016 14:25:19] "GET /static/admin/js/core.js HTTP/1.1" 200 8366
[03/Apr/2016 14:25:19] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
[03/Apr/2016 14:25:19] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 7171
[03/Apr/2016 14:25:19] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7693
[03/Apr/2016 14:25:19] "GET /static/admin/js/actions.js HTTP/1.1" 200 6259
[03/Apr/2016 14:25:19] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1538
[03/Apr/2016 14:25:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:25:19] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 247597
[03/Apr/2016 14:25:19] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 200 62474
[03/Apr/2016 14:25:20] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[03/Apr/2016 14:25:23] "GET /admin/main/match/add/ HTTP/1.1" 200 10449
[03/Apr/2016 14:25:23] "GET /static/admin/css/forms.css HTTP/1.1" 200 7750
[03/Apr/2016 14:25:23] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:25:23] "GET /static/admin/js/calendar.js HTTP/1.1" 200 6875
[03/Apr/2016 14:25:23] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 18563
[03/Apr/2016 14:25:23] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[03/Apr/2016 14:25:23] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
[03/Apr/2016 14:25:23] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[03/Apr/2016 14:25:23] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[03/Apr/2016 14:25:27] "GET /admin/main/match/ HTTP/1.1" 200 3154
[03/Apr/2016 14:25:28] "GET /admin/ HTTP/1.1" 200 4593
[03/Apr/2016 14:25:33] "GET /admin/main/tournament/ HTTP/1.1" 200 3189
[03/Apr/2016 14:25:33] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:25:35] "GET /admin/main/tournament/add/ HTTP/1.1" 200 5544
[03/Apr/2016 14:25:35] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:26:11] "POST /admin/main/tournament/add/ HTTP/1.1" 302 0
[03/Apr/2016 14:26:11] "GET /admin/main/tournament/ HTTP/1.1" 200 4546
[03/Apr/2016 14:26:12] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:26:12] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[03/Apr/2016 14:26:14] "GET /admin/main/tournament/add/ HTTP/1.1" 200 5544
[03/Apr/2016 14:26:17] "GET /admin/main/tournament/ HTTP/1.1" 200 4386
[03/Apr/2016 14:26:18] "GET /admin/main/tournament/add/ HTTP/1.1" 200 5544
[03/Apr/2016 14:26:19] "GET /admin/main/tournament/ HTTP/1.1" 200 4386
[03/Apr/2016 14:26:20] "GET /admin/ HTTP/1.1" 200 4928
[03/Apr/2016 14:26:22] "GET /admin/main/match/add/ HTTP/1.1" 200 10494
[03/Apr/2016 14:26:22] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 11:50:41
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Apr/2016 14:29:25] "GET /admin/main/match/add/ HTTP/1.1" 200 10489
[03/Apr/2016 14:29:25] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:29:25] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[03/Apr/2016 14:29:25] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[03/Apr/2016 14:29:26] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[03/Apr/2016 14:29:26] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[03/Apr/2016 14:29:26] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[03/Apr/2016 14:29:26] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:29:26] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:29:26] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:29:26] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
[03/Apr/2016 14:29:26] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[03/Apr/2016 14:29:32] "GET /admin/main/ HTTP/1.1" 200 3374
[03/Apr/2016 14:29:36] "GET /admin/main/team/add/ HTTP/1.1" 200 6165
[03/Apr/2016 14:29:36] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:29:51] "GET /admin/main/stadium/add/?_to_field=id&_popup=1 HTTP/1.1" 200 3136
[03/Apr/2016 14:29:51] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:30:05] "POST /admin/main/stadium/add/?_to_field=id&_popup=1 HTTP/1.1" 200 234
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:29:18
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:31:16
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f0f047ef2f0>
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/base.py", line 472, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
<class 'main.admin.MainAdmin'>: (admin.E027) The value of 'prepopulated_fields' refers to 'slug', which is not an attribute of 'main.Stadium'.
<class 'main.admin.MainAdmin'>: (admin.E027) The value of 'prepopulated_fields' refers to 'slug', which is not an attribute of 'main.Tournament'.
<class 'main.admin.MainAdmin'>: (admin.E030) The value of 'prepopulated_fields["slug"][0]' refers to 'title', which is not an attribute of 'main.Stadium'.
<class 'main.admin.MainAdmin'>: (admin.E030) The value of 'prepopulated_fields["slug"][0]' refers to 'title', which is not an attribute of 'main.Team'.
<class 'main.admin.MainAdmin'>: (admin.E030) The value of 'prepopulated_fields["slug"][0]' refers to 'title', which is not an attribute of 'main.Tournament'.

System check identified 5 issues (0 silenced).
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f1850d0f2f0>
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/base.py", line 472, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
<class 'main.admin.MainAdmin'>: (admin.E027) The value of 'prepopulated_fields' refers to 'slug', which is not an attribute of 'main.Tournament'.
<class 'main.admin.MainAdmin'>: (admin.E030) The value of 'prepopulated_fields["slug"][0]' refers to 'title', which is not an attribute of 'main.Team'.
<class 'main.admin.MainAdmin'>: (admin.E030) The value of 'prepopulated_fields["slug"][0]' refers to 'title', which is not an attribute of 'main.Tournament'.

System check identified 3 issues (0 silenced).
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f28a03322f0>
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/base.py", line 472, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
<class 'main.admin.MainAdmin'>: (admin.E030) The value of 'prepopulated_fields["slug"][0]' refers to 'title', which is not an attribute of 'main.Team'.
<class 'main.admin.MainAdmin'>: (admin.E030) The value of 'prepopulated_fields["slug"][0]' refers to 'title', which is not an attribute of 'main.Tournament'.

System check identified 2 issues (0 silenced).
Performing system checks...

[03/Apr/2016 14:37:13] "GET /admin/main/team/add/ HTTP/1.1" 200 6729
[03/Apr/2016 14:37:14] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:37:14] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:37:14] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:37:38] "POST /admin/main/team/add/ HTTP/1.1" 302 0
[03/Apr/2016 14:37:38] "GET /admin/main/team/ HTTP/1.1" 200 4464
[03/Apr/2016 14:37:38] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:37:41] "GET /admin/main/team/add/ HTTP/1.1" 200 6729
[03/Apr/2016 14:37:42] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:37:51] "GET /admin/main/stadium/add/?_to_field=id&_popup=1 HTTP/1.1" 200 3136
[03/Apr/2016 14:37:51] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:37:57] "POST /admin/main/stadium/add/?_to_field=id&_popup=1 HTTP/1.1" 200 232
[03/Apr/2016 14:38:12] "POST /admin/main/team/add/ HTTP/1.1" 302 0
[03/Apr/2016 14:38:12] "GET /admin/main/team/ HTTP/1.1" 200 4679
[03/Apr/2016 14:38:12] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:38:32] "GET /admin/main/team/add/ HTTP/1.1" 200 6766
[03/Apr/2016 14:38:32] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:38:38] "GET /admin/main/stadium/add/?_to_field=id&_popup=1 HTTP/1.1" 200 3136
[03/Apr/2016 14:38:38] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:38:45] "POST /admin/main/stadium/add/?_to_field=id&_popup=1 HTTP/1.1" 200 232
[03/Apr/2016 14:38:49] "POST /admin/main/team/add/ HTTP/1.1" 302 0
[03/Apr/2016 14:38:49] "GET /admin/main/team/ HTTP/1.1" 200 4896
[03/Apr/2016 14:38:49] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:38:52] "GET /admin/main/ HTTP/1.1" 200 3374
[03/Apr/2016 14:38:57] "GET /admin/main/match/ HTTP/1.1" 200 3154
[03/Apr/2016 14:38:57] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:38:59] "GET /admin/main/match/add/ HTTP/1.1" 200 10812
[03/Apr/2016 14:39:00] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:39:39] "POST /admin/main/match/add/ HTTP/1.1" 302 0
[03/Apr/2016 14:39:39] "GET /admin/main/match/ HTTP/1.1" 200 4481
[03/Apr/2016 14:39:39] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:39:41] "GET /admin/main/match/add/ HTTP/1.1" 200 10812
[03/Apr/2016 14:39:41] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:40:39] "POST /admin/main/match/add/ HTTP/1.1" 302 0
[03/Apr/2016 14:40:39] "GET /admin/main/match/ HTTP/1.1" 200 4706
[03/Apr/2016 14:40:39] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:37:12
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Apr/2016 14:41:13] "GET /admin/main/match/ HTTP/1.1" 200 4596
[03/Apr/2016 14:41:13] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:41:13] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:41:13] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:41:12
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:44:02
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:44:34
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:44:53
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /admin/main/match/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/db/models/options.py", line 580, in get_field
    return self.fields_map[field_name]
KeyError: '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/utils.py", line 274, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/utils.py", line 308, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/g7/.local/lib/python3.4/site-packages/django/db/models/options.py", line 582, in get_field
    raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Match has no field named '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/library.py", line 223, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 326, in result_list
    'results': list(results(cl))}
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 302, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 293, in __init__
    super(ResultList, self).__init__(*items)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 202, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/utils.py", line 290, in lookup_field
    value = attr()
  File "/home/g7/work/aqhorajuega/main/models.py", line 40, in __str__
    return self.team_a + ' - ' + self.team_b + str(self.local_time)
TypeError: unsupported operand type(s) for +: 'Team' and 'str'
[03/Apr/2016 14:45:08] "GET /admin/main/match/ HTTP/1.1" 500 293822
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:45:02
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /admin/main/match/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/db/models/options.py", line 580, in get_field
    return self.fields_map[field_name]
KeyError: '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/utils.py", line 274, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/utils.py", line 308, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/g7/.local/lib/python3.4/site-packages/django/db/models/options.py", line 582, in get_field
    raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Match has no field named '__str__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 172, in get_response
    response = response.render()
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/response.py", line 160, in render
    self.content = self.rendered_content
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/library.py", line 223, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 326, in result_list
    'results': list(results(cl))}
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 302, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 293, in __init__
    super(ResultList, self).__init__(*items)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/templatetags/admin_list.py", line 202, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/admin/utils.py", line 290, in lookup_field
    value = attr()
  File "/home/g7/work/aqhorajuega/main/models.py", line 40, in __str__
    return str(self.team_a) + ' - ' + self.team_b + str(self.local_time)
TypeError: Can't convert 'Team' object to str implicitly
[03/Apr/2016 14:45:28] "GET /admin/main/match/ HTTP/1.1" 500 293712
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:45:27
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Apr/2016 14:45:48] "GET /admin/main/match/ HTTP/1.1" 200 4618
[03/Apr/2016 14:45:48] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[03/Apr/2016 14:45:48] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[03/Apr/2016 14:45:48] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[03/Apr/2016 14:45:48] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[03/Apr/2016 14:45:48] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[03/Apr/2016 14:45:48] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:45:48] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[03/Apr/2016 14:45:48] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[03/Apr/2016 14:45:48] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[03/Apr/2016 14:45:48] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[03/Apr/2016 14:45:48] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[03/Apr/2016 14:45:48] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[03/Apr/2016 14:45:49] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:45:49] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:45:49] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[03/Apr/2016 14:45:49] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:45:46
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Apr/2016 14:46:18] "GET /admin/main/match/ HTTP/1.1" 200 4624
[03/Apr/2016 14:46:19] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:46:19] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:46:19] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:46:18
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Apr/2016 14:47:53] "GET /admin/main/match/ HTTP/1.1" 200 4627
[03/Apr/2016 14:47:53] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[03/Apr/2016 14:47:53] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[03/Apr/2016 14:47:53] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[03/Apr/2016 14:47:53] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[03/Apr/2016 14:47:53] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[03/Apr/2016 14:47:53] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[03/Apr/2016 14:47:54] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 14:47:54] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[03/Apr/2016 14:47:54] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[03/Apr/2016 14:47:54] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[03/Apr/2016 14:47:54] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[03/Apr/2016 14:47:54] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[03/Apr/2016 14:47:54] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:47:54] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:47:54] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 14:47:54] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 14:47:39
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Apr/2016 20:41:55] "GET /admin/main/match/add/ HTTP/1.1" 200 10816
[03/Apr/2016 20:41:55] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[03/Apr/2016 20:41:55] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[03/Apr/2016 20:41:55] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[03/Apr/2016 20:41:55] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[03/Apr/2016 20:41:55] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 20:41:56] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[03/Apr/2016 20:41:56] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[03/Apr/2016 20:41:56] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[03/Apr/2016 20:41:56] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[03/Apr/2016 20:41:56] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
[03/Apr/2016 20:42:18] "POST /admin/main/match/add/ HTTP/1.1" 302 0
[03/Apr/2016 20:42:18] "GET /admin/main/match/ HTTP/1.1" 200 5072
[03/Apr/2016 20:42:18] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 20:42:18] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 20:41:42
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[03/Apr/2016 20:43:59] "GET /admin/main/match/ HTTP/1.1" 200 4888
[03/Apr/2016 20:43:59] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 20:43:59] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[03/Apr/2016 20:43:59] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[03/Apr/2016 20:44:06] "GET /admin/main/match/add/ HTTP/1.1" 200 10816
[03/Apr/2016 20:44:06] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[03/Apr/2016 20:44:27] "POST /admin/main/match/add/ HTTP/1.1" 302 0
[03/Apr/2016 20:44:27] "GET /admin/main/match/ HTTP/1.1" 200 5336
[03/Apr/2016 20:44:27] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 20:43:52
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
April 03, 2016 - 23:57:11
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 00:08:33
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Not Found: /
[04/Apr/2016 21:47:35] "GET / HTTP/1.1" 404 2014
Not Found: /favicon.ico
[04/Apr/2016 21:47:36] "GET /favicon.ico HTTP/1.1" 404 2047
[04/Apr/2016 21:47:40] "GET /admin HTTP/1.1" 301 0
[04/Apr/2016 21:47:40] "GET /admin/ HTTP/1.1" 200 7555
[04/Apr/2016 21:47:41] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 21:47:41] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 434
[04/Apr/2016 21:47:41] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 21:47:41] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:47:41] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:47:41] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:47:41] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[04/Apr/2016 21:47:41] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[04/Apr/2016 21:47:44] "GET /admin/main/match/ HTTP/1.1" 200 5149
[04/Apr/2016 21:47:44] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[04/Apr/2016 21:47:44] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 21:47:44] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:47:44] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 21:47:44] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 21:47:44] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 21:47:44] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 21:47:44] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 21:47:44] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 21:47:44] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 21:47:44] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[04/Apr/2016 21:47:46] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11078
[04/Apr/2016 21:47:46] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:47:46] "GET /static/admin/css/forms.css HTTP/1.1" 200 7750
[04/Apr/2016 21:47:46] "GET /static/admin/js/calendar.js HTTP/1.1" 200 6875
[04/Apr/2016 21:47:46] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[04/Apr/2016 21:47:46] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 18563
[04/Apr/2016 21:47:46] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
[04/Apr/2016 21:47:46] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[04/Apr/2016 21:47:47] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 21:47:31
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[04/Apr/2016 21:48:13] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11472
[04/Apr/2016 21:48:13] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:48:13] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[04/Apr/2016 21:48:13] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 21:48:11
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[04/Apr/2016 21:49:33] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11448
[04/Apr/2016 21:49:33] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:49:33] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[04/Apr/2016 21:49:33] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[04/Apr/2016 21:49:33] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[04/Apr/2016 21:49:33] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[04/Apr/2016 21:49:33] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 21:49:31
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[04/Apr/2016 21:49:47] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11472
[04/Apr/2016 21:49:47] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:49:47] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:49:47] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:49:48] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:49:48] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:49:48] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:49:48] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[04/Apr/2016 21:49:48] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
[04/Apr/2016 21:49:59] "GET /admin/main/stadium/3/change/?_to_field=id&_popup=1 HTTP/1.1" 200 28620
[04/Apr/2016 21:49:59] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:50:06] "POST /admin/main/stadium/3/change/?_to_field=id&_popup=1 HTTP/1.1" 200 240
[04/Apr/2016 21:50:10] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11472
[04/Apr/2016 21:50:10] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:50:10] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:50:10] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:50:11] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[04/Apr/2016 21:50:11] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
[04/Apr/2016 21:50:59] "GET /admin/main/match/create HTTP/1.1" 301 0
[04/Apr/2016 21:50:59] "GET /admin/main/match/create/ HTTP/1.1" 302 0
Not Found: /admin/main/match/create/change/
[04/Apr/2016 21:50:59] "GET /admin/main/match/create/change/ HTTP/1.1" 404 1810
[04/Apr/2016 21:51:05] "GET /admin/main/match/change/ HTTP/1.1" 302 0
Not Found: /admin/main/match/change/change/
[04/Apr/2016 21:51:05] "GET /admin/main/match/change/change/ HTTP/1.1" 404 1810
[04/Apr/2016 21:51:08] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11472
[04/Apr/2016 21:51:09] "GET /admin/main/match/ HTTP/1.1" 200 5149
[04/Apr/2016 21:51:12] "GET /admin/main/match/add/ HTTP/1.1" 200 11186
[04/Apr/2016 21:51:12] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 21:49:45
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 21:52:55
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[04/Apr/2016 21:53:08] "GET /admin/main/match/ HTTP/1.1" 200 5149
[04/Apr/2016 21:53:09] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11480
[04/Apr/2016 21:53:10] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:53:13] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11480
[04/Apr/2016 21:53:13] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:53:13] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[04/Apr/2016 21:53:13] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 21:53:05
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[04/Apr/2016 21:53:58] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11459
[04/Apr/2016 21:53:58] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:53:58] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[04/Apr/2016 21:53:58] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:53:58] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:53:59] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:53:59] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:53:59] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:53:59] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[04/Apr/2016 21:53:59] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 21:53:56
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[04/Apr/2016 21:54:18] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11480
[04/Apr/2016 21:54:19] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:54:19] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[04/Apr/2016 21:54:19] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
[04/Apr/2016 21:54:25] "GET /admin/main/stadium/3/change/?_to_field=id&_popup=1 HTTP/1.1" 200 28620
[04/Apr/2016 21:54:26] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:54:36] "POST /admin/main/stadium/3/change/?_to_field=id&_popup=1 HTTP/1.1" 200 240
[04/Apr/2016 21:54:40] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11480
[04/Apr/2016 21:54:41] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:54:41] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[04/Apr/2016 21:54:41] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 21:54:18
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[04/Apr/2016 21:58:01] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11553
[04/Apr/2016 21:58:01] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 21:58:01] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[04/Apr/2016 21:58:01] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 21:58:01] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 21:58:01] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 21:58:01] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 21:58:01] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[04/Apr/2016 21:58:02] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 21:57:52
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[04/Apr/2016 22:03:04] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11480
[04/Apr/2016 22:03:05] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 22:03:05] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[04/Apr/2016 22:03:05] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[04/Apr/2016 22:03:05] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[04/Apr/2016 22:03:05] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 22:03:03
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[04/Apr/2016 22:03:55] "GET /admin/main/match/4/change/ HTTP/1.1" 200 11480
[04/Apr/2016 22:03:56] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[04/Apr/2016 22:03:56] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/js/vendor/xregexp/xregexp.min.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/js/calendar.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 304 0
[04/Apr/2016 22:03:56] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 22:03:53
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 22:06:06
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 04, 2016 - 22:09:26
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f2a28591ae8>
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/g7/work/aqhorajuega/aqhorajuega/urls.py", line 20, in <module>
    url(r'^main/', include('main.urls')),
  File "/home/g7/.local/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/g7/work/aqhorajuega/main/urls.py", line 3, in <module>
    from . import views
  File "/home/g7/work/aqhorajuega/main/views.py", line 3, in <module>
    import aqhorajuega.functions
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 26
    return pytz.timezone(̈́"Europe/Berlin")
                         ^
SyntaxError: invalid character in identifier
Performing system checks...

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f08fbde3ae8>
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/g7/work/aqhorajuega/aqhorajuega/urls.py", line 20, in <module>
    url(r'^main/', include('main.urls')),
  File "/home/g7/.local/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/g7/work/aqhorajuega/main/urls.py", line 3, in <module>
    from . import views
  File "/home/g7/work/aqhorajuega/main/views.py", line 3, in <module>
    import aqhorajuega.functions
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 26
    return pytz.timezone(̈́'Europe/Berlin')
                         ^
SyntaxError: invalid character in identifier
Performing system checks...

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[06/Apr/2016 22:09:46] "GET /admin/ HTTP/1.1" 200 7565
[06/Apr/2016 22:09:47] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[06/Apr/2016 22:09:47] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[06/Apr/2016 22:09:47] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[06/Apr/2016 22:09:48] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[06/Apr/2016 22:09:48] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[06/Apr/2016 22:09:48] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[06/Apr/2016 22:09:48] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[06/Apr/2016 22:09:48] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
Not Found: /favicon.ico
[06/Apr/2016 22:09:48] "GET /favicon.ico HTTP/1.1" 404 2047
[06/Apr/2016 22:10:14] "GET /main HTTP/1.1" 301 0
Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 6, in index
    return HttpResponse(aqhorajuega.functions.get_user_timezone(request))
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 10, in get_user_timezone
    lat_lon = g.lat_lon(get_client_ip(request))
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 209, in lat_lon
    return self.coords(query, ('latitude', 'longitude'))
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 197, in coords
    cdict = self.city(query)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 173, in city
    return City(self._city.city(enc_query))
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 105, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 168, in _model_for
    record = self._get(types, ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 164, in _get
    "The address %s is not in the database." % ip_address)
geoip2.errors.AddressNotFoundError: The address 127.0.0.1 is not in the database.
[06/Apr/2016 22:10:15] "GET /main/ HTTP/1.1" 500 87029
Performing system checks...

System check identified no issues (0 silenced).
April 06, 2016 - 22:09:38
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 06, 2016 - 22:11:37
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 6, in index
    return HttpResponse(aqhorajuega.functions.get_user_timezone(request))
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 14, in get_user_timezone
    lat_lon = g.lat_lon(ip)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 209, in lat_lon
    return self.coords(query, ('latitude', 'longitude'))
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 197, in coords
    cdict = self.city(query)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 172, in city
    enc_query = self._check_query(query, city=True)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 162, in _check_query
    query = socket.gethostbyname(query)
socket.gaierror: [Errno -2] Name or service not known
[06/Apr/2016 22:13:57] "GET /main/ HTTP/1.1" 500 79196
Performing system checks...

System check identified no issues (0 silenced).
April 06, 2016 - 22:13:55
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[06/Apr/2016 22:15:05] "GET /main/ HTTP/1.1" 200 11
Performing system checks...

System check identified no issues (0 silenced).
April 06, 2016 - 22:15:02
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[06/Apr/2016 22:15:21] "GET /main/ HTTP/1.1" 200 11
Performing system checks...

System check identified no issues (0 silenced).
April 06, 2016 - 22:15:16
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 06, 2016 - 22:15:44
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 06, 2016 - 22:16:09
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[06/Apr/2016 22:24:34] "GET /main/ HTTP/1.1" 200 13
[06/Apr/2016 22:24:38] "GET /main/ HTTP/1.1" 200 14
[06/Apr/2016 22:24:41] "GET /main/ HTTP/1.1" 200 14
[06/Apr/2016 22:24:44] "GET /main/ HTTP/1.1" 200 13
[06/Apr/2016 22:24:47] "GET /main/ HTTP/1.1" 200 13
[06/Apr/2016 22:24:49] "GET /main/ HTTP/1.1" 200 14
[06/Apr/2016 22:24:53] "GET /main/ HTTP/1.1" 200 14
[06/Apr/2016 22:24:56] "GET /main/ HTTP/1.1" 200 14
Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 6, in index
    return HttpResponse(aqhorajuega.functions.get_user_timezone(request))
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 14, in get_user_timezone
    lat_lon = g.lat_lon(ip)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 209, in lat_lon
    return self.coords(query, ('latitude', 'longitude'))
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 197, in coords
    cdict = self.city(query)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 173, in city
    return City(self._city.city(enc_query))
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 105, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 168, in _model_for
    record = self._get(types, ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 164, in _get
    "The address %s is not in the database." % ip_address)
geoip2.errors.AddressNotFoundError: The address 103.83.112.89 is not in the database.
[06/Apr/2016 22:24:59] "GET /main/ HTTP/1.1" 500 87459
[06/Apr/2016 22:25:02] "GET /main/ HTTP/1.1" 200 13
[06/Apr/2016 22:25:05] "GET /main/ HTTP/1.1" 200 14
Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 6, in index
    return HttpResponse(aqhorajuega.functions.get_user_timezone(request))
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 14, in get_user_timezone
    lat_lon = g.lat_lon(ip)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 209, in lat_lon
    return self.coords(query, ('latitude', 'longitude'))
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 197, in coords
    cdict = self.city(query)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 173, in city
    return City(self._city.city(enc_query))
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 105, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 168, in _model_for
    record = self._get(types, ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 164, in _get
    "The address %s is not in the database." % ip_address)
geoip2.errors.AddressNotFoundError: The address 45.179.88.229 is not in the database.
[06/Apr/2016 22:25:07] "GET /main/ HTTP/1.1" 500 87459
[06/Apr/2016 22:25:11] "GET /main/ HTTP/1.1" 200 14
Performing system checks...

System check identified no issues (0 silenced).
April 06, 2016 - 22:24:23
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
hola
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[06/Apr/2016 22:27:52] "GET /main/ HTTP/1.1" 200 17
[06/Apr/2016 22:27:56] "GET /main/ HTTP/1.1" 200 13
[06/Apr/2016 22:27:59] "GET /main/ HTTP/1.1" 200 14
[06/Apr/2016 22:28:02] "GET /main/ HTTP/1.1" 200 13
[06/Apr/2016 22:28:04] "GET /main/ HTTP/1.1" 200 13
[06/Apr/2016 22:28:08] "GET /main/ HTTP/1.1" 200 13
[06/Apr/2016 22:28:10] "GET /main/ HTTP/1.1" 200 30
Performing system checks...

System check identified no issues (0 silenced).
April 06, 2016 - 22:25:39
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
hola
hola
hola
hola
hola
hola
hola
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 6, in index
    return HttpResponse(aqhorajuega.functions.get_user_timezone(request))
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 13, in get_user_timezone
    ip = '{0}.{1}.{2}.{3}'.format([random.randrange(255) for x in range(4)])
IndexError: tuple index out of range
[06/Apr/2016 22:30:14] "GET /main/ HTTP/1.1" 500 62335
Performing system checks...

System check identified no issues (0 silenced).
April 06, 2016 - 22:29:40
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 6, in index
    return HttpResponse(aqhorajuega.functions.get_user_timezone(request))
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 13, in get_user_timezone
    ip = '{0}.{1}.{2}.{3}'.format((random.randrange(255) for x in range(4)))
IndexError: tuple index out of range
[06/Apr/2016 22:30:36] "GET /main/ HTTP/1.1" 500 62470
Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 6, in index
    return HttpResponse(aqhorajuega.functions.get_user_timezone(request))
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 13, in get_user_timezone
    ip = '{0}.{1}.{2}.{3}'.format((random.randrange(255) for x in range(4)))
IndexError: tuple index out of range
[06/Apr/2016 22:30:44] "GET /main/ HTTP/1.1" 500 62470
Performing system checks...

System check identified no issues (0 silenced).
April 06, 2016 - 22:30:34
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[18/Apr/2016 22:29:26] "GET /main HTTP/1.1" 301 0
[18/Apr/2016 22:29:27] "GET /main/ HTTP/1.1" 200 16
Not Found: /favicon.ico
[18/Apr/2016 22:29:27] "GET /favicon.ico HTTP/1.1" 404 2047
[18/Apr/2016 22:29:35] "GET /main/ HTTP/1.1" 200 19
Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 22:29:18
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 22:31:10
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f38feb87ae8>
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/g7/work/aqhorajuega/aqhorajuega/urls.py", line 20, in <module>
    url(r'^main/', include('main.urls')),
  File "/home/g7/.local/lib/python3.4/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/g7/work/aqhorajuega/main/urls.py", line 3, in <module>
    from . import views
  File "/home/g7/work/aqhorajuega/main/views.py", line 8
    for
      ^
SyntaxError: invalid syntax
Performing system checks...

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 11, in index
    string += match.local_time() + '<br>'
TypeError: local_time() missing 1 required positional argument: 'timezone'
[18/Apr/2016 22:37:26] "GET /main/ HTTP/1.1" 500 59937
Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 22:37:14
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 12, in index
    string += match.local_time(timezone) + '<br>'
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'str'
[18/Apr/2016 22:38:05] "GET /main/ HTTP/1.1" 500 60184
Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 22:38:02
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 22:39:09
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 22:39:25
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[18/Apr/2016 22:39:59] "GET /main/ HTTP/1.1" 200 137
Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 22:39:51
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 22:40:59
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[18/Apr/2016 22:41:23] "GET /main/ HTTP/1.1" 200 245
[18/Apr/2016 22:59:58] "GET /main/ HTTP/1.1" 200 247
[18/Apr/2016 23:00:02] "GET /main/ HTTP/1.1" 200 247
Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 10, in index
    timezone = aqhorajuega.functions.get_user_timezone(request)
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 14, in get_user_timezone
    lat_lon = g.lat_lon(ip)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 209, in lat_lon
    return self.coords(query, ('latitude', 'longitude'))
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 197, in coords
    cdict = self.city(query)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 173, in city
    return City(self._city.city(enc_query))
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 105, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 168, in _model_for
    record = self._get(types, ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 164, in _get
    "The address %s is not in the database." % ip_address)
geoip2.errors.AddressNotFoundError: The address 252.240.26.244 is not in the database.
[18/Apr/2016 23:00:05] "GET /main/ HTTP/1.1" 500 88910
Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 10, in index
    timezone = aqhorajuega.functions.get_user_timezone(request)
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 14, in get_user_timezone
    lat_lon = g.lat_lon(ip)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 209, in lat_lon
    return self.coords(query, ('latitude', 'longitude'))
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 197, in coords
    cdict = self.city(query)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 173, in city
    return City(self._city.city(enc_query))
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 105, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 168, in _model_for
    record = self._get(types, ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 164, in _get
    "The address %s is not in the database." % ip_address)
geoip2.errors.AddressNotFoundError: The address 227.185.171.176 is not in the database.
[18/Apr/2016 23:00:20] "GET /main/ HTTP/1.1" 500 88921
[18/Apr/2016 23:00:23] "GET /main/ HTTP/1.1" 200 245
Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 22:41:17
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7ffba0026d08>
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/g7/.local/lib/python3.4/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: staticfiles
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 23:39:07
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 23:47:10
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 508, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 13, in index
    return render(request, 'main/index.html', {'string': string})
  File "/home/g7/.local/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 510, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 572, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static'. Did you forget to register or load this tag?
[18/Apr/2016 23:47:44] "GET /main/ HTTP/1.1" 500 120012
[18/Apr/2016 23:48:20] "GET /main/ HTTP/1.1" 200 534
[18/Apr/2016 23:48:20] "GET /static/main/jquery.countdown.min.js HTTP/1.1" 200 5057
Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 10, in index
    timezone = aqhorajuega.functions.get_user_timezone(request)
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 14, in get_user_timezone
    lat_lon = g.lat_lon(ip)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 209, in lat_lon
    return self.coords(query, ('latitude', 'longitude'))
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 197, in coords
    cdict = self.city(query)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 173, in city
    return City(self._city.city(enc_query))
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 105, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 168, in _model_for
    record = self._get(types, ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 164, in _get
    "The address %s is not in the database." % ip_address)
geoip2.errors.AddressNotFoundError: The address 241.27.25.83 is not in the database.
[18/Apr/2016 23:48:56] "GET /main/ HTTP/1.1" 500 88899
[18/Apr/2016 23:49:02] "GET /main/ HTTP/1.1" 200 534
[18/Apr/2016 23:49:02] "GET /static/main/jquery.countdown.min.js HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 23:47:27
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 13, in index
    return render(request, 'main/index.html', {'matches': matches, 'timezone': timezone})
  File "/home/g7/.local/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/defaulttags.py", line 886, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 487, in parse
    raise self.error(token, e)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 485, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 601, in compile_filter
    return FilterExpression(token, self)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 701, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'match.stadium_time()'
[18/Apr/2016 23:53:43] "GET /main/ HTTP/1.1" 500 142522
Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 13, in index
    return render(request, 'main/index.html', {'matches': matches, 'timezone': timezone})
  File "/home/g7/.local/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/defaulttags.py", line 886, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 487, in parse
    raise self.error(token, e)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 485, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 601, in compile_filter
    return FilterExpression(token, self)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 701, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(timezone)' from 'match.local_time(timezone)'
[18/Apr/2016 23:54:03] "GET /main/ HTTP/1.1" 500 143515
Performing system checks...

System check identified no issues (0 silenced).
April 18, 2016 - 23:50:48
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f479715dc80>
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/g7/.local/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/g7/.local/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/g7/work/aqhorajuega/main/models.py", line 39
    timezone=
            ^
SyntaxError: invalid syntax
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 19, 2016 - 00:08:34
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Performing system checks...

System check identified no issues (0 silenced).
April 19, 2016 - 00:09:00
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 11, in index
    return render(request, 'main/index.html', {'matches': matches, 'timezone': Match.timezone})
  File "/home/g7/.local/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/defaulttags.py", line 220, in render
    nodelist.append(node.render_annotated(context))
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 1043, in render
    output = self.filter_expression.resolve(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 709, in resolve
    obj = self.var.resolve(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 913, in _resolve_lookup
    current = current()
  File "/home/g7/work/aqhorajuega/main/models.py", line 47, in stadium_time
    return self.local_time(self.stadium.timezone)
TypeError: local_time() takes 1 positional argument but 2 were given
[19/Apr/2016 00:09:32] "GET /main/ HTTP/1.1" 500 129174
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2016 - 00:09:17
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[19/Apr/2016 00:11:12] "GET /main/ HTTP/1.1" 200 546
[19/Apr/2016 00:11:13] "GET /static/main/jquery.countdown.min.js HTTP/1.1" 304 0
[19/Apr/2016 00:11:29] "GET /main/ HTTP/1.1" 200 543
[19/Apr/2016 00:11:30] "GET /static/main/jquery.countdown.min.js HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2016 - 00:10:51
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[19/Apr/2016 00:11:57] "GET /main/ HTTP/1.1" 200 545
[19/Apr/2016 00:11:58] "GET /static/main/jquery.countdown.min.js HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2016 - 00:11:50
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[19/Apr/2016 00:12:38] "GET /main/ HTTP/1.1" 200 498
[19/Apr/2016 00:12:38] "GET /static/main/jquery.countdown.min.js HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2016 - 00:12:36
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[19/Apr/2016 00:13:01] "GET /main/ HTTP/1.1" 200 546
[19/Apr/2016 00:13:01] "GET /static/main/jquery.countdown.min.js HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2016 - 00:12:58
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

[19/Apr/2016 00:15:10] "GET /main/ HTTP/1.1" 200 546
[19/Apr/2016 00:15:11] "GET /static/main/jquery.countdown.min.js HTTP/1.1" 304 0
[19/Apr/2016 00:15:17] "GET /main/ HTTP/1.1" 200 546
[19/Apr/2016 00:15:18] "GET /static/main/jquery.countdown.min.js HTTP/1.1" 304 0
[19/Apr/2016 00:15:21] "GET /main/ HTTP/1.1" 200 546
[19/Apr/2016 00:15:21] "GET /static/main/jquery.countdown.min.js HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2016 - 00:15:02
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 9, in index
    Match.timezone = aqhorajuega.functions.get_user_timezone(request)
  File "/home/g7/work/aqhorajuega/aqhorajuega/functions.py", line 14, in get_user_timezone
    lat_lon = g.lat_lon(ip)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 209, in lat_lon
    return self.coords(query, ('latitude', 'longitude'))
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 197, in coords
    cdict = self.city(query)
  File "/home/g7/.local/lib/python3.4/site-packages/django/contrib/gis/geoip2/base.py", line 173, in city
    return City(self._city.city(enc_query))
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 105, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 168, in _model_for
    record = self._get(types, ip_address)
  File "/home/g7/.local/lib/python3.4/site-packages/geoip2/database.py", line 164, in _get
    "The address %s is not in the database." % ip_address)
geoip2.errors.AddressNotFoundError: The address 185.151.144.53 is not in the database.
[19/Apr/2016 00:17:05] "GET /main/ HTTP/1.1" 500 88557
[19/Apr/2016 00:17:10] "GET /main/ HTTP/1.1" 200 543
[19/Apr/2016 00:17:11] "GET /static/main/jquery.countdown.min.js HTTP/1.1" 304 0
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2016 - 00:16:59
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Internal Server Error: /main/
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/g7/work/aqhorajuega/main/views.py", line 11, in index
    return render(request, 'main/index.html', {'matches': matches, 'timezone': Match.timezone})
  File "/home/g7/.local/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/defaulttags.py", line 1190, in load
    parser.add_library(lib)
  File "/home/g7/.local/lib/python3.4/site-packages/django/template/base.py", line 594, in add_library
    self.tags.update(lib.tags)
AttributeError: type object 'Library' has no attribute 'tags'
[19/Apr/2016 22:11:09] "GET /main/ HTTP/1.1" 500 124359
Not Found: /favicon.ico
[19/Apr/2016 22:11:10] "GET /favicon.ico HTTP/1.1" 404 2047
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2016 - 22:11:06
Django version 1.9.5, using settings 'aqhorajuega.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f1ba5af46a8>
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/g7/.local/lib/python3.4/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: main
/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f792c45a6a8>
Traceback (most recent call last):
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/g7/.local/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/g7/.local/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/g7/.local/lib/python3.4/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: main
